import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import type { Place, Store, Task, TaskState } from './types';
import { demo, STORAGE_KEY } from './data';

const placeLabels:Record<Place,string>={pool:'Пул',week:'Неделя',today:'Сегодня',now:'Сейчас',done:'Готово'};
const stateLabels:Record<Exclude<TaskState,null>,string>={waiting:'Жду',delegated:'Делегировано',blocked:'Блок'};
const blankTask=(title:string,place:Place,order:number):Task=>({id:crypto.randomUUID(),title,place,state:null,stoppedAt:'',nextStep:'',waitingFor:'',result:'',attentionAt:null,order,createdAt:Date.now(),completedAt:null});
const load=():Store=>{try{const v=localStorage.getItem(STORAGE_KEY);return v?JSON.parse(v):demo}catch{return demo}};

function Editable({value,placeholder,onSave,className=''}:{value:string;placeholder:string;onSave:(v:string)=>void;className?:string}){
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState(value);
  useEffect(()=>setDraft(value),[value]);
  const save=()=>{onSave(draft.trim());setEditing(false)};
  if(editing)return <textarea autoFocus className={`inline-input ${className}`} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={save} onKeyDown={e=>{if(e.key==='Escape'){setDraft(value);setEditing(false)}if(e.key==='Enter'&&(!e.shiftKey||e.metaKey||e.ctrlKey)){e.preventDefault();save()}}}/>;
  return <button className={`editable ${className} ${!value?'empty':''}`} onClick={()=>setEditing(true)} title="Нажмите, чтобы изменить">{value||placeholder}</button>;
}

function App(){
  const [store,setStore]=useState<Store>(load),[view,setView]=useState<Exclude<Place,'now'>>('today');
  const [newOpen,setNewOpen]=useState(false),[brain,setBrain]=useState(''),[toast,setToast]=useState('');
  const [deleted,setDeleted]=useState<Task|null>(null),[switchTo,setSwitchTo]=useState<string|null>(null),[showNext,setShowNext]=useState(false);
  const [dragId,setDragId]=useState<string|null>(null); const toastTimer=useRef<number | undefined>(undefined);
  useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(store)),[store]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA'].includes(t.tagName)){e.preventDefault();setNewOpen(true)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
  const notify=(s:string)=>{setToast(s);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),2600)};
  const tasks=store.tasks; const current=tasks.find(t=>t.place==='now');
  const update=(id:string,patch:Partial<Task>)=>setStore(s=>({tasks:s.tasks.map(t=>t.id===id?{...t,...patch}:t)}));
  const move=(id:string,place:Place)=>update(id,{place,state:place==='done'?null:tasks.find(t=>t.id===id)?.state,completedAt:place==='done'?Date.now():null,order:Math.max(0,...tasks.filter(t=>t.place===place).map(t=>t.order))+1});
  const requestStart=(id:string)=>current&&current.id!==id?setSwitchTo(id):start(id);
  const start=(id:string,context?:Partial<Task>)=>{setStore(s=>({tasks:s.tasks.map(t=>t.id===id?{...t,place:'now',state:null}:t.place==='now'?{...t,...context,place:'today'}:t)}));setSwitchTo(null);setShowNext(false);setView('today')};
  const complete=(id:string)=>{const was=current?.id===id;move(id,'done');if(was)setShowNext(true)};
  const setState=(id:string,state:Exclude<TaskState,null>)=>{update(id,{state,place:'today'});if(current?.id===id)setShowNext(true)};
  const add=(title:string,place:Place)=>{if(!title.trim())return;const task=blankTask(title.trim(),place,Math.max(0,...tasks.map(t=>t.order))+1);setStore(s=>({tasks:[...s.tasks.map(t=>place==='now'&&t.place==='now'?{...t,place:'today' as Place}:t),task]}));setNewOpen(false);if(place==='now')setView('today');notify(place==='pool'?'Задача сохранена в Пуле':'Задача создана')};
  const remove=(task:Task)=>{setDeleted(task);setStore(s=>({tasks:s.tasks.filter(t=>t.id!==task.id)}));notify('Задача удалена')};
  const available=tasks.filter(t=>t.place==='today'&&!t.state).sort((a,b)=>a.order-b.order);
  const passive=tasks.filter(t=>t.place==='today'&&t.state).sort((a,b)=>a.order-b.order);
  const counts=useMemo(()=>({today:tasks.filter(t=>t.place==='today'||t.place==='now').length,week:tasks.filter(t=>t.place==='week').length,pool:tasks.filter(t=>t.place==='pool').length,done:tasks.filter(t=>t.place==='done').length}),[tasks]);
  const drop=(target:Place,before?:Task)=>{if(!dragId)return;const siblings=tasks.filter(t=>t.place===target&&t.id!==dragId).sort((a,b)=>a.order-b.order);const idx=before?siblings.findIndex(t=>t.id===before.id):siblings.length;siblings.splice(idx,0,tasks.find(t=>t.id===dragId)!);setStore(s=>({tasks:s.tasks.map(t=>{const i=siblings.findIndex(x=>x.id===t.id);return i>=0?{...t,place:target,order:i}:t})}));setDragId(null)};

  const TaskRow=({task,muted=false}:{task:Task;muted?:boolean})=><article className={`task-row ${muted?'muted':''}`} draggable onDragStart={()=>setDragId(task.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(task.place,task)}>
    <div className="drag" aria-label="Перетащить">⠿</div><div className="task-main"><div className="title-line"><Editable value={task.title} placeholder="Название" onSave={title=>update(task.id,{title})} className="task-title"/>{task.state&&<span className={`status ${task.state}`}>{stateLabels[task.state]}</span>}{task.place==='done'&&<span className="status done">Готово</span>}</div>
    <div className="context"><span><b>Точка</b><Editable value={task.stoppedAt} placeholder="Где остановился?" onSave={stoppedAt=>update(task.id,{stoppedAt})}/></span><span className="next"><b>Дальше</b><Editable value={task.nextStep} placeholder="Добавить следующий шаг" onSave={nextStep=>update(task.id,{nextStep})}/></span>{(task.waitingFor||task.state)&&<span><b>Жду</b><Editable value={task.waitingFor} placeholder="Кого или чего?" onSave={waitingFor=>update(task.id,{waitingFor})}/></span>}</div></div>
    <div className="actions">{task.place==='done'?<button onClick={()=>move(task.id,'pool')}>Восстановить</button>:<><button className="primary-mini" onClick={()=>requestStart(task.id)}>Начать</button>{task.place!=='today'&&<button onClick={()=>move(task.id,'today')}>Сегодня</button>}{task.place!=='week'&&<button onClick={()=>move(task.id,'week')}>Неделя</button>}{task.place!=='pool'&&<button onClick={()=>move(task.id,'pool')}>В пул</button>}<button onClick={()=>complete(task.id)}>Готово</button></>}<button className="icon-danger" onClick={()=>remove(task)} aria-label="Удалить">×</button></div>
  </article>;

  return <div className="app"><header><div className="brand"><span className="brand-mark">T</span><strong>TODAY</strong></div><nav>{(['today','week','pool','done'] as const).map(p=><button className={view===p?'active':''} onClick={()=>setView(p)} key={p}>{placeLabels[p]} <span>{counts[p]}</span></button>)}</nav><button className="new-btn" onClick={()=>setNewOpen(true)}><span>＋</span> Новая задача <kbd>N</kbd></button></header>
    <main><div className="brain"><span>＋</span><input value={brain} onChange={e=>setBrain(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&brain.trim()){add(brain,'pool');setBrain('')}}} placeholder="Что ещё надо не забыть?"/><small>Enter — сохранить в Пул</small></div>
    {view==='today'?<section className="page fade"><div className="page-heading"><div><p className="eyebrow">Фокус дня</p><h1>Сегодня</h1></div><p>Не всё сразу. Только то, что важно сейчас.</p></div>
      <section className="now-card"><div className="section-label"><span className="live-dot"/> Сейчас</div>{current?<><div className="now-top"><Editable value={current.title} placeholder="Название" onSave={title=>update(current.id,{title})} className="now-title"/><span className="focus-pill">В фокусе</span></div><div className="now-grid"><div><label>Где остановился</label><Editable value={current.stoppedAt} placeholder="Зафиксировать точку остановки" onSave={stoppedAt=>update(current.id,{stoppedAt})}/></div><div><label>Следующий шаг</label><Editable value={current.nextStep} placeholder="Что сделать дальше?" onSave={nextStep=>update(current.id,{nextStep})}/></div><div><label>Результат</label><Editable value={current.result} placeholder="Что будет считаться готовым?" onSave={result=>update(current.id,{result})}/></div>{current.waitingFor&&<div><label>Жду</label><Editable value={current.waitingFor} placeholder="Кого или чего?" onSave={waitingFor=>update(current.id,{waitingFor})}/></div>}</div><div className="now-actions"><button className="solid" onClick={()=>setNewOpen(true)}>↗ Переключиться</button><button onClick={()=>complete(current.id)}>✓ Завершить</button><i/><button onClick={()=>setState(current.id,'waiting')}>◷ Жду</button><button onClick={()=>setState(current.id,'delegated')}>↗ Делегировать</button><button onClick={()=>setState(current.id,'blocked')}>⊘ Блок</button></div></>:<div className="empty-now"><div>◎</div><h3>Фокус свободен</h3><p>Выберите следующую задачу или начните новую.</p><button className="solid" onClick={()=>setNewOpen(true)}>Начать новую задачу</button></div>}</section>
      {(showNext||!current)&&available.length>0&&<section className="next-box"><div><p className="eyebrow">Мягкий старт</p><h3>Что дальше?</h3></div><div>{available.slice(0,3).map(t=><button onClick={()=>requestStart(t.id)} key={t.id}>{t.title}<span>→</span></button>)}</div></section>}
      <section className="list-section"><div className="section-head"><div><h2>Можно продолжить <span>{available.length}</span></h2><p>Действие сейчас на вашей стороне</p></div></div>{available.length?available.map(t=><TaskRow task={t} key={t.id}/>):<Empty text="Доступных задач пока нет"/>}</section>
      <section className="list-section passive"><div className="section-head"><div><h2>Жду / Делегировано / Блок <span>{passive.length}</span></h2><p>Задачи, которым пока не нужно ваше внимание</p></div></div>{passive.map(t=><TaskRow task={t} muted key={t.id}/>)}</section>
    </section>:<ListPage place={view} tasks={tasks} onDrop={()=>drop(view)}>{tasks.filter(t=>t.place===view).sort((a,b)=>view==='done'?(b.completedAt||0)-(a.completedAt||0):a.order-b.order).map(t=><TaskRow task={t} key={t.id}/>)}</ListPage>}</main>
    {newOpen&&<NewModal close={()=>setNewOpen(false)} add={add}/>} {switchTo&&current&&<SwitchModal task={current} close={()=>setSwitchTo(null)} save={context=>start(switchTo,context)}/>} 
    {(toast||deleted)&&<div className="toast"><span>✓</span>{toast||'Задача удалена'}{deleted&&<button onClick={()=>{setStore(s=>({tasks:[...s.tasks,deleted]}));setDeleted(null);setToast('Задача возвращена')}}>Undo</button>}<button className="toast-x" onClick={()=>{setToast('');setDeleted(null)}}>×</button></div>}
    <footer><span>Все данные хранятся только на этом устройстве</span><span><i/> Сохранено</span></footer></div>;
}

function Empty({text}:{text:string}){return <div className="empty-list">○<span>{text}</span></div>}
function ListPage({place,tasks,onDrop,children}:{place:Exclude<Place,'now'|'today'>;tasks:Task[];onDrop:()=>void;children:ReactNode}){const copy={week:['Неделя','Ближайший горизонт — без календаря и давления.'],pool:['Пул','Спокойное место для всего, что не хочется держать в голове.'],done:['Готово','Недавно завершённое — без отчётов и аналитики.']}[place];const n=tasks.filter(t=>t.place===place).length;return <section className="page fade" onDragOver={e=>e.preventDefault()} onDrop={onDrop}><div className="page-heading"><div><p className="eyebrow">{place==='pool'?'Внешняя память':place==='week'?'Горизонт внимания':'Тихий архив'}</p><h1>{copy[0]}</h1></div><p>{copy[1]}</p></div><div className="section-head"><h2>{place==='done'?'Завершённые':'Задачи'} <span>{n}</span></h2></div>{n?children:<Empty text="Здесь пока спокойно"/>}</section>}
function NewModal({close,add}:{close:()=>void;add:(t:string,p:Place)=>void}){const [title,setTitle]=useState(''),[place,setPlace]=useState<Place>('pool');return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={e=>{e.preventDefault();add(title,place)}}><button type="button" className="modal-x" onClick={close}>×</button><p className="eyebrow">Новая мысль</p><h2>Новая задача</h2><label>Название</label><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Что нужно сделать?"/><label>Куда добавить</label><div className="choice">{([['pool','В Пул'],['week','На неделю'],['today','На сегодня'],['now','Начать сейчас']] as [Place,string][]).map(([p,l])=><button type="button" className={place===p?'selected':''} onClick={()=>setPlace(p)} key={p}>{l}</button>)}</div><div className="modal-actions"><button type="button" onClick={close}>Отмена</button><button className="solid" disabled={!title.trim()}>Создать задачу</button></div></form></div>}
function SwitchModal({task,close,save}:{task:Task;close:()=>void;save:(p:Partial<Task>)=>void}){const [stoppedAt,setStopped]=useState(task.stoppedAt),[nextStep,setNext]=useState(task.nextStep),[waitingFor,setWaiting]=useState(task.waitingFor);return <div className="overlay"><form className="modal switch-modal" onSubmit={e=>{e.preventDefault();save({stoppedAt,nextStep,waitingFor})}}><button type="button" className="modal-x" onClick={close}>×</button><div className="pause-icon">Ⅱ</div><p className="eyebrow">Перед переключением</p><h2>Сохраните точку остановки</h2><p className="modal-copy">Чтобы вернуться к «{task.title}» без потери контекста.</p><label>Где остановился?</label><input autoFocus value={stoppedAt} onChange={e=>setStopped(e.target.value)} placeholder="Коротко: что уже сделано"/><label>Следующий шаг?</label><input value={nextStep} onChange={e=>setNext(e.target.value)} placeholder="Первое действие при возвращении"/><label>Жду кого / чего?</label><input value={waitingFor} onChange={e=>setWaiting(e.target.value)} placeholder="Оставьте пустым, если не ждёте"/><div className="modal-actions"><button type="button" onClick={close}>Остаться</button><button className="solid">Сохранить и переключиться →</button></div></form></div>}
export default App;
